### PR TITLE
Build a ME domaincfg file (on ARCHER2)

### PR DESCRIPTION
**Pull request by jpolton**
Workflow to generate ME domain_cfg.nc file from scratch.
Built for ARCHER2 (as a portability test)

* Requires input bathymetry and coordinates
* Uses python envelope generation
* Uses ME builder using NEMO DOMAINcfg tool

Process documented in [wiki](https://github.com/JMMP-Group/CO9_AMM15/wiki/Make-ME-domain-configuration-file)

**Acceptance criteria:**
* Follow the wiki instructions. Does it work?

### CODE REVIEW

**Comment by jpolton** [comment]
@anwiseNOCL I think I need to hand this to you to have a play with. I written some comprehensive notes in the wiki (as above). It takes you through a complete build of the domain_cfg.nc file using ME coordinates, up to the point where it fails.... The problem is in a file called `mes.F90` when it wants to broadcast arrays across all processors. I imagine it is an ARCHER2 thing, as it works for Diego on MONSooN, and would probably work on LIVLJOBS too. He has also been thinking about FORTRAN fixes. 
I've passed the inputs files to Diego to have a try on MONSooN, just in case it is a Jeff-error.
Discussion on https://github.com/JMMP-Group/CO9_AMM15/issues/25

My goal was to get it working on ARCHER2 to make the ME tool more easy for other people adopt.

**Comment by anwiseNOCL** [comment]
@jpolton Ok i'll give it a go and see if i can replicate.

**Comment by davbyr** [comment]
@jpolton Not sure if you're still looking for a review on this but for the sake of record, it worked for me.

Issues that cropped up:

> Make sure there are no NaNs in the bathymetry input. Replace with zeros using `ncap2` or `xarray` first.

**Comment by jpolton** [comment]
> @jpolton Not sure if you're still looking for a review on this but for the sake of record, it worked for me.
> 
> Issues that cropped up:
> 
> > Make sure there are no NaNs in the bathymetry input. Replace with zeros using `ncap2` or `xarray` first.

@davbyr I am. I ought to merge this. Since it has a file that Diego has updated. Do you have any thoughts of the different directory structures? Diego puts everything into a MEs_envs directory at the top of the tree, whereas I squirrel things into some subdirectories associated with more generic configuration building.

**Comment by jpolton** [comment]
@oceandie @endaodea @davbyr @anwiseNOCL I am making an executive decision to slightly restructure the code directory in order to better future proof this repository as a more permanent and evolving `CO_AMM15` repo rather than a shorter lived `CO9_AMM15` repository.  

In reality all this means is that I've created a new high level directory to put all our excellent domain_cfg stuff into:
DOMAIN_cfg/MEs_envs
DOMAN_cfg/domwad

The [wiki](https://github.com/JMMP-Group/CO9_AMM15/wiki/Make-ME-domain-configuration-file) documentation works with this structure, but has not been updated/tested with Diego's most recent enhancements, but it should be fairly straight forward check/test when the next person goes through the process.

**Pull request merged**
